### ISSUE TITLE
Torch no grad

### ISSUE THREAD

**Issue by michele-milesi** [kc-ml2/SimpleDreamer#7]
https://github.com/kc-ml2/SimpleDreamer/blob/1800326b8fee2d78a0dffd7bcae27f6221896c2d/dreamer/algorithms/dreamer.py#L245

I would like to ask why torch.no_grad decorator is not used in this method.
I tried running your agent, but the execution would raise the "cuda out of memory" runtime error without the torch.no_grad decorator.

Thank you in advance

**Comment by michele-milesi** [comment]
I run an experiment with `@torch.no_grad()` decorator for the `environment_interaction()` method: the memory is stable at 21.92 GiB and the agent correctly learns to play the game (CarRacing).

<img width="923" alt="memory performance" src="https://user-images.githubusercontent.com/74559684/230588513-55ef4a13-c4ee-4ed5-b80c-8a2e54400198.png">
<img width="287" alt="agent score" src="https://user-images.githubusercontent.com/74559684/230588509-3826330f-e3a6-4f1f-9304-ed7962d6e069.png">

**Comment by seolhokim** [comment]
Thank you again! :) I guess it is caused by non time limit(or dynamic time limit) environment. no_grad decorator is not essential part in algorithm, but we also reported those environments could cause out of memory error. and your suggestion looks proper to me.

If you have any further questions, please feel free to let us know.
